// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/shared/Button.vue')['default']
    Form: typeof import('./src/components/shared/Form.vue')['default']
    FormItem: typeof import('./src/components/shared/FormItem.vue')['default']
    Input: typeof import('./src/components/shared/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/shared/Textarea.vue')['default']
  }
}
